### ISSUE TITLE
Dimension mismatch during forward()

### ISSUE THREAD

**Issue by agnonchik** [ssjatmhmy/pytorch-resnet-ssd#1]
Hi, which version of Python and Pytorch did you use for testing?

I uncommented test() in ssd.py and got an error:

Traceback (most recent call last):
  File "ssd.py", line 84, in <module>
    test()
  File "ssd.py", line 76, in test
    loc_preds, cls_preds = net(Variable(torch.randn(2,3,300,300)))
  File "/home/val/anaconda3/envs/torch-0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "ssd.py", line 63, in forward
    fms = self.base_network(x)
  File "/home/val/anaconda3/envs/torch-0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/val/src/pytorch/pytorch-resnet-ssd/resnet_base.py", line 202, in forward
    x = self.layer4(x)
  File "/home/val/anaconda3/envs/torch-0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/val/anaconda3/envs/torch-0.4/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/val/anaconda3/envs/torch-0.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/val/src/pytorch/pytorch-resnet-ssd/resnet_base.py", line 100, in forward
    out += residual
RuntimeError: The expanded size of the tensor (17) must match the existing size (19) at non-singleton dimension 3

Please advise.

**Comment by ZLeopard** [comment]
i meet this problem too, do you figure out it?

**Comment by R00Kie-Liu** [comment]
if you want to use dilation convolution, you have to revise the code in class Bottleneck:
```   
    def __init__(self, inplanes, planes, stride=1, dilation=1, downsample=None):
        super(Bottleneck, self).__init__()
        self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=1, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)

        # set the padding=2 when dilation=2 to maintain the feature map size:

        if dilation == 2:
            self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=stride, dilation=dilation,
                               padding=2, bias=False)
        else:
            self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=stride, dilation=dilation,
                               padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.conv3 = nn.Conv2d(planes, planes * 4, kernel_size=1, bias=False)
        self.bn3 = nn.BatchNorm2d(planes * 4)
        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample
        self.stride = stride
```
